# Generated by Django 6.0.1 on 2026-02-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not paid', 'Not Paid'), ('ready to ship', 'Ready To Ship'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='not paid', max_length=25),
        ),
    ]
